<?php 
 //2017-05-31 14:38:33
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '139.205.180.228',
  'REMOTE_PORT' => '14015',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_HOST' => '/',
  'HTTP_CONNECTION' => 'keep-alive',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 MicroMessenger/6.5.2.501 NetType/WIFI WindowsWechat QBCore/3.43.493.400 QQBrowser/9.0.2524.400',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-us;q=0.6,en;q=0.5;q=0.4',
  'HTTP_COOKIE' => 'PHPSESSID=81m9hp0636flsq32m01n0sphi1',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496212712.989372,
  'REQUEST_TIME' => 1496212712,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 14:38:40
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '101.226.125.100',
  'REMOTE_PORT' => '41521',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Mobile/14D27 MicroMessenger/6.5.5 NetType/WIFI Language/en',
  'HTTP_ACCEPT' => '*/*',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch, br',
  'HTTP_REFERER' => 'http://wx.taitaiqi.cn/addon/LdhQguess/mobile/index/mpid/1/pid/10',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4',
  'HTTP_HOST' => '/',
  'HTTP_CONNECTION' => 'keep-alive',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496212720.5292549,
  'REQUEST_TIME' => 1496212720,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 14:48:20
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '182.140.175.142',
  'REMOTE_PORT' => '55057',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/wxpic,image/sharpp,*/*;q=0.8',
  'HTTP_ACCEPT_ENCODING' => 'gzip',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,en-US;q=0.8',
  'HTTP_CONNECTION' => 'close',
  'HTTP_COOKIE' => 'PHPSESSID=hfbj08hiuqa4i7ja22o84ukkk7',
  'HTTP_HOST' => '/',
  'HTTP_REFERER' => 'http://a.taitaiqi.cn/ab_a/1/10',
  'HTTP_UPGRADE_INSECURE_REQUESTS' => '1',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Linux; Android 7.0; BLN-AL10 Build/HONORBLN-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043220 Safari/537.36 MicroMessenger/6.5.7.1041 NetType/WIFI Language/zh_CN',
  'HTTP_X_FORWARDED_FOR' => '139.205.180.228',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496213300.7716429,
  'REQUEST_TIME' => 1496213300,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 14:48:21
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10&t=1496213300&code=0515QY2L0Bkjs32VS2ZK0qoZ2L05QY2P&state=',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10?t=1496213300&code=0515QY2L0Bkjs32VS2ZK0qoZ2L05QY2P&state=',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '182.140.175.142',
  'REMOTE_PORT' => '41024',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/wxpic,image/sharpp,*/*;q=0.8',
  'HTTP_ACCEPT_ENCODING' => 'gzip',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,en-US;q=0.8',
  'HTTP_CONNECTION' => 'close',
  'HTTP_COOKIE' => 'PHPSESSID=hfbj08hiuqa4i7ja22o84ukkk7',
  'HTTP_HOST' => '/',
  'HTTP_UPGRADE_INSECURE_REQUESTS' => '1',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Linux; Android 7.0; BLN-AL10 Build/HONORBLN-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043220 Safari/537.36 MicroMessenger/6.5.7.1041 NetType/WIFI Language/zh_CN',
  'HTTP_X_FORWARDED_FOR' => '139.205.180.228',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496213301.0863891,
  'REQUEST_TIME' => 1496213301,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 14:48:30
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10&t=1496213300',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10?t=1496213300',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '180.163.1.46',
  'REMOTE_PORT' => '51055',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Linux; Android 6.0.1; OPPO R9s Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/37.0.0.0 Mobile MQQBrowser/6.9 TBS/036906 Safari/537.36 MicroMessenger/6.5.4.1000 NetType/4G Language/zh_CN',
  'HTTP_ACCEPT' => '*/*',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch, br',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4',
  'HTTP_HOST' => '/',
  'HTTP_CONNECTION' => 'keep-alive',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496213310.2032721,
  'REQUEST_TIME' => 1496213310,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 14:50:00
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '139.205.180.228',
  'REMOTE_PORT' => '14399',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_HOST' => '/',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 MicroMessenger/6.5.2.501 NetType/WIFI WindowsWechat QBCore/3.43.493.400 QQBrowser/9.0.2524.400',
  'HTTP_REFERER' => 'http://a.taitaiqi.cn/ab_a/1/10',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-us;q=0.6,en;q=0.5;q=0.4',
  'HTTP_COOKIE' => 'PHPSESSID=81m9hp0636flsq32m01n0sphi1',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496213400.714273,
  'REQUEST_TIME' => 1496213400,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 14:50:00
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10&t=1496213400&code=021AAKUf0YcYXA12A7Wf0e7GUf0AAKUg&state=',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10?t=1496213400&code=021AAKUf0YcYXA12A7Wf0e7GUf0AAKUg&state=',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '139.205.180.228',
  'REMOTE_PORT' => '14399',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_HOST' => '/',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 MicroMessenger/6.5.2.501 NetType/WIFI WindowsWechat QBCore/3.43.493.400 QQBrowser/9.0.2524.400',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-us;q=0.6,en;q=0.5;q=0.4',
  'HTTP_COOKIE' => 'PHPSESSID=81m9hp0636flsq32m01n0sphi1',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496213400.925889,
  'REQUEST_TIME' => 1496213400,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 14:50:01
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10&t=1496213400&code=051JlbJg0jIzrB1oLOHg0LjXIg0JlbJU&state=',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10?t=1496213400&code=051JlbJg0jIzrB1oLOHg0LjXIg0JlbJU&state=',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '139.205.180.228',
  'REMOTE_PORT' => '14408',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_HOST' => '/',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 MicroMessenger/6.5.2.501 NetType/WIFI WindowsWechat QBCore/3.43.493.400 QQBrowser/9.0.2524.400',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-us;q=0.6,en;q=0.5;q=0.4',
  'HTTP_COOKIE' => 'PHPSESSID=81m9hp0636flsq32m01n0sphi1',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496213400.9777551,
  'REQUEST_TIME' => 1496213400,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 14:50:13
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10&t=1496213400',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10?t=1496213400',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '101.226.33.240',
  'REMOTE_PORT' => '57354',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 MicroMessenger/6.5.2.501 NetType/WIFI WindowsWechat QBCore/3.43.27.400 QQBrowser/9.0.2524.400',
  'HTTP_ACCEPT' => '*/*',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch, br',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4',
  'HTTP_HOST' => '/',
  'HTTP_CONNECTION' => 'keep-alive',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496213413.721307,
  'REQUEST_TIME' => 1496213413,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 14:51:23
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '139.205.180.228',
  'REMOTE_PORT' => '14491',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_HOST' => '/',
  'HTTP_CONNECTION' => 'keep-alive',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 MicroMessenger/6.5.2.501 NetType/WIFI WindowsWechat QBCore/3.43.493.400 QQBrowser/9.0.2524.400',
  'HTTP_REFERER' => 'http://a.taitaiqi.cn/ab_a/1/10',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-us;q=0.6,en;q=0.5;q=0.4',
  'HTTP_COOKIE' => 'PHPSESSID=81m9hp0636flsq32m01n0sphi1',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496213483.6484089,
  'REQUEST_TIME' => 1496213483,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 14:54:14
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '139.205.180.228',
  'REMOTE_PORT' => '14598',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_HOST' => '/',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 MicroMessenger/6.5.2.501 NetType/WIFI WindowsWechat QBCore/3.43.493.400 QQBrowser/9.0.2524.400',
  'HTTP_REFERER' => 'http://a.taitaiqi.cn/ab_a/1/10',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-us;q=0.6,en;q=0.5;q=0.4',
  'HTTP_COOKIE' => 'PHPSESSID=81m9hp0636flsq32m01n0sphi1',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496213654.625252,
  'REQUEST_TIME' => 1496213654,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 14:54:14
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10&t=1496213654&code=001vQGu90xgAtu1Ehdt906EFu90vQGuB&state=',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10?t=1496213654&code=001vQGu90xgAtu1Ehdt906EFu90vQGuB&state=',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '139.205.180.228',
  'REMOTE_PORT' => '14598',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_HOST' => '/',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 MicroMessenger/6.5.2.501 NetType/WIFI WindowsWechat QBCore/3.43.493.400 QQBrowser/9.0.2524.400',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-us;q=0.6,en;q=0.5;q=0.4',
  'HTTP_COOKIE' => 'PHPSESSID=81m9hp0636flsq32m01n0sphi1',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496213654.84196,
  'REQUEST_TIME' => 1496213654,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 14:54:15
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10&t=1496213654&code=061pTLxB0F2Rwc27nsAB0Y5NxB0pTLxm&state=',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10?t=1496213654&code=061pTLxB0F2Rwc27nsAB0Y5NxB0pTLxm&state=',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '139.205.180.228',
  'REMOTE_PORT' => '14601',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_HOST' => '/',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 MicroMessenger/6.5.2.501 NetType/WIFI WindowsWechat QBCore/3.43.493.400 QQBrowser/9.0.2524.400',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-us;q=0.6,en;q=0.5;q=0.4',
  'HTTP_COOKIE' => 'PHPSESSID=81m9hp0636flsq32m01n0sphi1',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496213654.8986471,
  'REQUEST_TIME' => 1496213654,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 14:54:24
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10&t=1496213654',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10?t=1496213654',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '101.226.66.172',
  'REMOTE_PORT' => '58746',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Mobile/14D27 MicroMessenger/6.5.5 NetType/WIFI Language/zh_CN',
  'HTTP_ACCEPT' => '*/*',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch, br',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4',
  'HTTP_HOST' => '/',
  'HTTP_CONNECTION' => 'keep-alive',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496213664.3411069,
  'REQUEST_TIME' => 1496213664,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 15:00:32
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '182.140.175.142',
  'REMOTE_PORT' => '45101',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/wxpic,image/sharpp,*/*;q=0.8',
  'HTTP_ACCEPT_ENCODING' => 'gzip',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,en-US;q=0.8',
  'HTTP_CONNECTION' => 'close',
  'HTTP_COOKIE' => 'PHPSESSID=hfbj08hiuqa4i7ja22o84ukkk7',
  'HTTP_HOST' => '/',
  'HTTP_REFERER' => 'http://a.taitaiqi.cn/ab_a/1/10',
  'HTTP_UPGRADE_INSECURE_REQUESTS' => '1',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Linux; Android 7.0; BLN-AL10 Build/HONORBLN-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043220 Safari/537.36 MicroMessenger/6.5.7.1041 NetType/WIFI Language/zh_CN',
  'HTTP_X_FORWARDED_FOR' => '139.205.180.228',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496214032.7473021,
  'REQUEST_TIME' => 1496214032,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 15:00:33
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10&t=1496214032&code=061TIJsk2p55eH0l1Xpk2c45tk2TIJs5&state=',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10?t=1496214032&code=061TIJsk2p55eH0l1Xpk2c45tk2TIJs5&state=',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '182.140.175.142',
  'REMOTE_PORT' => '62835',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/wxpic,image/sharpp,*/*;q=0.8',
  'HTTP_ACCEPT_ENCODING' => 'gzip',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,en-US;q=0.8',
  'HTTP_CONNECTION' => 'close',
  'HTTP_COOKIE' => 'PHPSESSID=hfbj08hiuqa4i7ja22o84ukkk7',
  'HTTP_HOST' => '/',
  'HTTP_UPGRADE_INSECURE_REQUESTS' => '1',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Linux; Android 7.0; BLN-AL10 Build/HONORBLN-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043220 Safari/537.36 MicroMessenger/6.5.7.1041 NetType/WIFI Language/zh_CN',
  'HTTP_X_FORWARDED_FOR' => '139.205.180.228',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496214033.05036,
  'REQUEST_TIME' => 1496214033,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 15:01:01
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '139.205.180.228',
  'REMOTE_PORT' => '14848',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_HOST' => '/',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 MicroMessenger/6.5.2.501 NetType/WIFI WindowsWechat QBCore/3.43.493.400 QQBrowser/9.0.2524.400',
  'HTTP_REFERER' => 'http://a.taitaiqi.cn/ab_a/1/10',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-us;q=0.6,en;q=0.5;q=0.4',
  'HTTP_COOKIE' => 'PHPSESSID=81m9hp0636flsq32m01n0sphi1',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496214061.9117551,
  'REQUEST_TIME' => 1496214061,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 15:01:02
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10&t=1496214061&code=05155LeW1ZqYoT0AEveW1MPqeW155LeH&state=',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10?t=1496214061&code=05155LeW1ZqYoT0AEveW1MPqeW155LeH&state=',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '139.205.180.228',
  'REMOTE_PORT' => '14848',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_HOST' => '/',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 MicroMessenger/6.5.2.501 NetType/WIFI WindowsWechat QBCore/3.43.493.400 QQBrowser/9.0.2524.400',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-us;q=0.6,en;q=0.5;q=0.4',
  'HTTP_COOKIE' => 'PHPSESSID=81m9hp0636flsq32m01n0sphi1',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496214062.1507909,
  'REQUEST_TIME' => 1496214062,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 15:01:03
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10&t=1496214061&code=031XgZTT1jx0v91AsFTT1rwTTT1XgZTz&state=',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10?t=1496214061&code=031XgZTT1jx0v91AsFTT1rwTTT1XgZTz&state=',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '139.205.180.228',
  'REMOTE_PORT' => '14856',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_HOST' => '/',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 MicroMessenger/6.5.2.501 NetType/WIFI WindowsWechat QBCore/3.43.493.400 QQBrowser/9.0.2524.400',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-us;q=0.6,en;q=0.5;q=0.4',
  'HTTP_COOKIE' => 'PHPSESSID=81m9hp0636flsq32m01n0sphi1',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496214062.1949539,
  'REQUEST_TIME' => 1496214062,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 15:01:23
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '182.140.175.142',
  'REMOTE_PORT' => '40069',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/wxpic,image/sharpp,*/*;q=0.8',
  'HTTP_ACCEPT_ENCODING' => 'gzip',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,en-US;q=0.8',
  'HTTP_CONNECTION' => 'close',
  'HTTP_COOKIE' => 'PHPSESSID=hfbj08hiuqa4i7ja22o84ukkk7',
  'HTTP_HOST' => '/',
  'HTTP_REFERER' => 'http://a.taitaiqi.cn/ab_a/1/10',
  'HTTP_UPGRADE_INSECURE_REQUESTS' => '1',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Linux; Android 7.0; BLN-AL10 Build/HONORBLN-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043220 Safari/537.36 MicroMessenger/6.5.7.1041 NetType/WIFI Language/zh_CN',
  'HTTP_X_FORWARDED_FOR' => '139.205.180.228',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496214083.009732,
  'REQUEST_TIME' => 1496214083,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 15:01:47
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/8',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/8',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '182.140.175.142',
  'REMOTE_PORT' => '64916',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/8',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/wxpic,image/sharpp,*/*;q=0.8',
  'HTTP_ACCEPT_ENCODING' => 'gzip',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,en-US;q=0.8',
  'HTTP_CONNECTION' => 'close',
  'HTTP_COOKIE' => 'PHPSESSID=s7lm3pqdbfg8e6c32qch5una26',
  'HTTP_HOST' => '/',
  'HTTP_REFERER' => 'http://a.taitaiqi.cn/ab_a/1/8',
  'HTTP_UPGRADE_INSECURE_REQUESTS' => '1',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Linux; Android 7.0; BLN-AL10 Build/HONORBLN-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043220 Safari/537.36 MicroMessenger/6.5.7.1041 NetType/WIFI Language/zh_CN',
  'HTTP_X_FORWARDED_FOR' => '139.205.180.228',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496214107.473983,
  'REQUEST_TIME' => 1496214107,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 15:01:47
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/8&t=1496214107&code=041MbRal2r9BdI0O0k9l2fMWal2MbRab&state=',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/8?t=1496214107&code=041MbRal2r9BdI0O0k9l2fMWal2MbRab&state=',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '182.140.175.142',
  'REMOTE_PORT' => '56989',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/8',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/wxpic,image/sharpp,*/*;q=0.8',
  'HTTP_ACCEPT_ENCODING' => 'gzip',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,en-US;q=0.8',
  'HTTP_CONNECTION' => 'close',
  'HTTP_COOKIE' => 'PHPSESSID=s7lm3pqdbfg8e6c32qch5una26',
  'HTTP_HOST' => '/',
  'HTTP_UPGRADE_INSECURE_REQUESTS' => '1',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Linux; Android 7.0; BLN-AL10 Build/HONORBLN-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043220 Safari/537.36 MicroMessenger/6.5.7.1041 NetType/WIFI Language/zh_CN',
  'HTTP_X_FORWARDED_FOR' => '139.205.180.228',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496214107.8885739,
  'REQUEST_TIME' => 1496214107,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 15:01:57
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/8',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/8',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '180.153.201.79',
  'REMOTE_PORT' => '46355',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/8',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Linux; Android 4.4.4; HUAWEI ALE-CL00 Build/HuaweiALE-CL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043024 Safari/537.36 MicroMessenger/6.5.4.1000 NetType/4G Language/zh_CN',
  'HTTP_ACCEPT' => '*/*',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch, br',
  'HTTP_REFERER' => 'http://wx.taitaiqi.cn/addon/LdhQguess/mobile/index/mpid/1/pid/8',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4',
  'HTTP_HOST' => '/',
  'HTTP_CONNECTION' => 'keep-alive',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496214117.4150369,
  'REQUEST_TIME' => 1496214117,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 15:01:57
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/8&t=1496214107&code=041MbRal2r9BdI0O0k9l2fMWal2MbRab&state=',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/8?t=1496214107&code=041MbRal2r9BdI0O0k9l2fMWal2MbRab&state=',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '182.140.175.142',
  'REMOTE_PORT' => '58503',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/8',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/wxpic,image/sharpp,*/*;q=0.8',
  'HTTP_ACCEPT_ENCODING' => 'gzip',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,en-US;q=0.8',
  'HTTP_CACHE_CONTROL' => 'max-age=0',
  'HTTP_CONNECTION' => 'close',
  'HTTP_COOKIE' => 'PHPSESSID=s7lm3pqdbfg8e6c32qch5una26',
  'HTTP_HOST' => '/',
  'HTTP_UPGRADE_INSECURE_REQUESTS' => '1',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Linux; Android 7.0; BLN-AL10 Build/HONORBLN-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043220 Safari/537.36 MicroMessenger/6.5.7.1041 NetType/WIFI Language/zh_CN',
  'HTTP_X_FORWARDED_FOR' => '139.205.180.228',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496214117.850456,
  'REQUEST_TIME' => 1496214117,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 15:02:25
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10&t=1496214061',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10?t=1496214061',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '180.153.201.66',
  'REMOTE_PORT' => '43817',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Mobile/14D27 MicroMessenger/6.5.5 NetType/WIFI Language/en',
  'HTTP_ACCEPT' => '*/*',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch, br',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4',
  'HTTP_HOST' => '/',
  'HTTP_CONNECTION' => 'keep-alive',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496214145.5477469,
  'REQUEST_TIME' => 1496214145,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 15:03:14
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/8',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/8',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '101.226.66.172',
  'REMOTE_PORT' => '55058',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/8',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Mobile/14D27 MicroMessenger/6.5.5 NetType/WIFI Language/zh_CN',
  'HTTP_ACCEPT' => '*/*',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch, br',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4',
  'HTTP_HOST' => '/',
  'HTTP_CONNECTION' => 'keep-alive',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496214194.1501429,
  'REQUEST_TIME' => 1496214194,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 15:03:26
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/8',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/8',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '182.140.175.142',
  'REMOTE_PORT' => '59112',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/8',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/wxpic,image/sharpp,*/*;q=0.8',
  'HTTP_ACCEPT_ENCODING' => 'gzip',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,en-US;q=0.8',
  'HTTP_CONNECTION' => 'close',
  'HTTP_COOKIE' => 'PHPSESSID=msmj0krbpes9s1sgtl2i34dp05',
  'HTTP_HOST' => '/',
  'HTTP_REFERER' => 'http://a.taitaiqi.cn/ab_a/1/8',
  'HTTP_UPGRADE_INSECURE_REQUESTS' => '1',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Linux; Android 7.0; BLN-AL10 Build/HONORBLN-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043220 Safari/537.36 MicroMessenger/6.5.7.1041 NetType/WIFI Language/zh_CN',
  'HTTP_X_FORWARDED_FOR' => '139.205.180.228',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496214206.242466,
  'REQUEST_TIME' => 1496214206,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 15:03:26
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/8&t=1496214206&code=031QCNxC0Kwbed2RIByC0kw4yC0QCNx7&state=',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/8?t=1496214206&code=031QCNxC0Kwbed2RIByC0kw4yC0QCNx7&state=',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '182.140.175.142',
  'REMOTE_PORT' => '33524',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/8',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/wxpic,image/sharpp,*/*;q=0.8',
  'HTTP_ACCEPT_ENCODING' => 'gzip',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,en-US;q=0.8',
  'HTTP_CONNECTION' => 'close',
  'HTTP_COOKIE' => 'PHPSESSID=msmj0krbpes9s1sgtl2i34dp05',
  'HTTP_HOST' => '/',
  'HTTP_UPGRADE_INSECURE_REQUESTS' => '1',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Linux; Android 7.0; BLN-AL10 Build/HONORBLN-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043220 Safari/537.36 MicroMessenger/6.5.7.1041 NetType/WIFI Language/zh_CN',
  'HTTP_X_FORWARDED_FOR' => '139.205.180.228',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496214206.6006689,
  'REQUEST_TIME' => 1496214206,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 15:03:36
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/8&t=1496214206',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/8?t=1496214206',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '180.153.160.24',
  'REMOTE_PORT' => '51310',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/8',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Linux; Android 6.0.1; OPPO R9s Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/37.0.0.0 Mobile MQQBrowser/6.9 TBS/036906 Safari/537.36 MicroMessenger/6.5.4.1000 NetType/4G Language/zh_CN',
  'HTTP_ACCEPT' => '*/*',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch, br',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4',
  'HTTP_HOST' => '/',
  'HTTP_CONNECTION' => 'keep-alive',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496214216.526463,
  'REQUEST_TIME' => 1496214216,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 15:08:28
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/8',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/8',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '140.207.185.112',
  'REMOTE_PORT' => '44287',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/8',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Mobile/14D27 MicroMessenger/6.5.5 NetType/WIFI Language/en',
  'HTTP_ACCEPT' => '*/*',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch, br',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4',
  'HTTP_HOST' => '/',
  'HTTP_CONNECTION' => 'keep-alive',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496214508.599771,
  'REQUEST_TIME' => 1496214508,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 15:54:15
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '139.205.180.228',
  'REMOTE_PORT' => '13320',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_HOST' => '/',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 MicroMessenger/6.5.2.501 NetType/WIFI WindowsWechat QBCore/3.43.493.400 QQBrowser/9.0.2524.400',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-us;q=0.6,en;q=0.5;q=0.4',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496217255.045615,
  'REQUEST_TIME' => 1496217255,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 15:54:15
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10&t=1496217255&code=031BqeA21iot3N1uQvA21T3dA21BqeAt&state=',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10?t=1496217255&code=031BqeA21iot3N1uQvA21T3dA21BqeAt&state=',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '139.205.180.228',
  'REMOTE_PORT' => '13320',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_HOST' => '/',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 MicroMessenger/6.5.2.501 NetType/WIFI WindowsWechat QBCore/3.43.493.400 QQBrowser/9.0.2524.400',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-us;q=0.6,en;q=0.5;q=0.4',
  'HTTP_COOKIE' => 'PHPSESSID=hb0o972duvp2d2cc27ge4t7mk1',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496217255.3269789,
  'REQUEST_TIME' => 1496217255,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 15:54:25
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10&t=1496217255',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10?t=1496217255',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '101.226.33.228',
  'REMOTE_PORT' => '56489',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Mobile/14D27 MicroMessenger/6.5.5 NetType/WIFI Language/en',
  'HTTP_ACCEPT' => '*/*',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch, br',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4',
  'HTTP_HOST' => '/',
  'HTTP_CONNECTION' => 'keep-alive',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496217265.302433,
  'REQUEST_TIME' => 1496217265,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 16:24:23
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/8',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/8',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '180.153.201.15',
  'REMOTE_PORT' => '42392',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/8',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Linux; Android 4.4.4; Coolpad Y82-520 Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36 MicroMessenger/6.5.4.1000 NetType/4G Language/zh_CN',
  'HTTP_ACCEPT' => '*/*',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch, br',
  'HTTP_REFERER' => 'http://wx.taitaiqi.cn/addon/LdhQguess/mobile/index/mpid/1/pid/8',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4',
  'HTTP_HOST' => '/',
  'HTTP_CONNECTION' => 'keep-alive',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496219063.145623,
  'REQUEST_TIME' => 1496219063,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 16:51:43
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '182.140.175.142',
  'REMOTE_PORT' => '45953',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/wxpic,image/sharpp,*/*;q=0.8',
  'HTTP_ACCEPT_ENCODING' => 'gzip',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,en-US;q=0.8',
  'HTTP_CONNECTION' => 'close',
  'HTTP_COOKIE' => 'PHPSESSID=hfbj08hiuqa4i7ja22o84ukkk7',
  'HTTP_HOST' => '/',
  'HTTP_UPGRADE_INSECURE_REQUESTS' => '1',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Linux; Android 7.0; BLN-AL10 Build/HONORBLN-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043220 Safari/537.36 MicroMessenger/6.5.7.1041 NetType/WIFI Language/zh_CN',
  'HTTP_X_FORWARDED_FOR' => '139.205.180.228',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496220703.529618,
  'REQUEST_TIME' => 1496220703,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 21:18:57
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '139.205.180.228',
  'REMOTE_PORT' => '13668',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_HOST' => '/',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 MicroMessenger/6.5.2.501 NetType/WIFI WindowsWechat QBCore/3.43.493.400 QQBrowser/9.0.2524.400',
  'HTTP_REFERER' => 'http://a.taitaiqi.cn/ab_a/1/10',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-us;q=0.6,en;q=0.5;q=0.4',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496236737.446553,
  'REQUEST_TIME' => 1496236737,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 21:18:57
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10&t=1496236737&code=0116tqvA1Dd65i0X2LyA1PhqvA16tqv5&state=',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10?t=1496236737&code=0116tqvA1Dd65i0X2LyA1PhqvA16tqv5&state=',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '139.205.180.228',
  'REMOTE_PORT' => '13668',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_HOST' => '/',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 MicroMessenger/6.5.2.501 NetType/WIFI WindowsWechat QBCore/3.43.493.400 QQBrowser/9.0.2524.400',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-us;q=0.6,en;q=0.5;q=0.4',
  'HTTP_COOKIE' => 'PHPSESSID=86ra7qcgks6v7ds5556rfk8vi1',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496236737.879492,
  'REQUEST_TIME' => 1496236737,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 21:18:58
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10&t=1496236737&code=051VCmJc1ImJns0RWGMc1IZiJc1VCmJY&state=',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10?t=1496236737&code=051VCmJc1ImJns0RWGMc1IZiJc1VCmJY&state=',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '139.205.180.228',
  'REMOTE_PORT' => '13671',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_HOST' => '/',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 MicroMessenger/6.5.2.501 NetType/WIFI WindowsWechat QBCore/3.43.493.400 QQBrowser/9.0.2524.400',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-us;q=0.6,en;q=0.5;q=0.4',
  'HTTP_COOKIE' => 'PHPSESSID=86ra7qcgks6v7ds5556rfk8vi1',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496236737.9259551,
  'REQUEST_TIME' => 1496236737,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-05-31 21:19:07
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10&t=1496236737',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10?t=1496236737',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '101.226.65.107',
  'REMOTE_PORT' => '39781',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Mobile/14D27 MicroMessenger/6.5.5 NetType/WIFI Language/en',
  'HTTP_ACCEPT' => '*/*',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch, br',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4',
  'HTTP_HOST' => '/',
  'HTTP_CONNECTION' => 'keep-alive',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496236747.556592,
  'REQUEST_TIME' => 1496236747,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-06-01 11:35:07
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '139.205.180.228',
  'REMOTE_PORT' => '13876',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_HOST' => '/',
  'HTTP_CONNECTION' => 'keep-alive',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 MicroMessenger/6.5.2.501 NetType/WIFI WindowsWechat QBCore/3.43.493.400 QQBrowser/9.0.2524.400',
  'HTTP_REFERER' => 'http://a.taitaiqi.cn/ab_a/1/10',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-us;q=0.6,en;q=0.5;q=0.4',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496288107.3248191,
  'REQUEST_TIME' => 1496288107,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-06-01 11:35:07
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10&t=1496288107&code=0211KLp40eGI5F1Ubnr40WBDp401KLpv&state=',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10?t=1496288107&code=0211KLp40eGI5F1Ubnr40WBDp401KLpv&state=',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '139.205.180.228',
  'REMOTE_PORT' => '13876',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_HOST' => '/',
  'HTTP_CONNECTION' => 'keep-alive',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 MicroMessenger/6.5.2.501 NetType/WIFI WindowsWechat QBCore/3.43.493.400 QQBrowser/9.0.2524.400',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-us;q=0.6,en;q=0.5;q=0.4',
  'HTTP_COOKIE' => 'PHPSESSID=piqltcjfvl6m600ldhs2equf45',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496288107.7737229,
  'REQUEST_TIME' => 1496288107,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-06-01 11:35:08
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10&t=1496288107&code=081Yux8U1D0gNT0jr67U1BqG8U1Yux8b&state=',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10?t=1496288107&code=081Yux8U1D0gNT0jr67U1BqG8U1Yux8b&state=',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '139.205.180.228',
  'REMOTE_PORT' => '13880',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_HOST' => '/',
  'HTTP_CONNECTION' => 'keep-alive',
  'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 MicroMessenger/6.5.2.501 NetType/WIFI WindowsWechat QBCore/3.43.493.400 QQBrowser/9.0.2524.400',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-us;q=0.6,en;q=0.5;q=0.4',
  'HTTP_COOKIE' => 'PHPSESSID=piqltcjfvl6m600ldhs2equf45',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496288107.820389,
  'REQUEST_TIME' => 1496288107,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-06-01 11:35:17
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10&t=1496288107',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10?t=1496288107',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '101.226.61.207',
  'REMOTE_PORT' => '37602',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 MicroMessenger/6.5.2.501 NetType/WIFI WindowsWechat QBCore/3.43.27.400 QQBrowser/9.0.2524.400',
  'HTTP_ACCEPT' => '*/*',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch, br',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4',
  'HTTP_HOST' => '/',
  'HTTP_CONNECTION' => 'keep-alive',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496288117.2351151,
  'REQUEST_TIME' => 1496288117,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-06-01 11:35:17
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '101.226.66.179',
  'REMOTE_PORT' => '60870',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Mobile/14D27 MicroMessenger/6.5.5 NetType/WIFI Language/en',
  'HTTP_ACCEPT' => '*/*',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch, br',
  'HTTP_REFERER' => 'http://wx.taitaiqi.cn/addon/LdhQguess/mobile/index/mpid/1/pid/10',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4',
  'HTTP_HOST' => '/',
  'HTTP_CONNECTION' => 'keep-alive',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496288117.4278381,
  'REQUEST_TIME' => 1496288117,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-06-01 11:36:49
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '180.153.201.79',
  'REMOTE_PORT' => '46057',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Mobile/14D27 MicroMessenger/6.5.5 NetType/WIFI Language/zh_CN',
  'HTTP_ACCEPT' => '*/*',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch, br',
  'HTTP_REFERER' => 'http://wx.taitaiqi.cn/addon/LdhQguess/mobile/index/mpid/1/pid/10',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4',
  'HTTP_HOST' => '/',
  'HTTP_CONNECTION' => 'keep-alive',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496288209.401922,
  'REQUEST_TIME' => 1496288209,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-06-01 11:40:55
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '61.151.226.16',
  'REMOTE_PORT' => '45467',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Linux; Android 6.0.1; OPPO R9s Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/37.0.0.0 Mobile MQQBrowser/6.9 TBS/036906 Safari/537.36 MicroMessenger/6.5.4.1000 NetType/4G Language/zh_CN',
  'HTTP_ACCEPT' => '*/*',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch, br',
  'HTTP_REFERER' => 'http://wx.taitaiqi.cn/addon/LdhQguess/mobile/index/mpid/1/pid/10',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4',
  'HTTP_HOST' => '/',
  'HTTP_CONNECTION' => 'keep-alive',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496288455.7740309,
  'REQUEST_TIME' => 1496288455,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-06-01 15:30:30
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '101.226.89.119',
  'REMOTE_PORT' => '40471',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Linux; Android 4.4.4; HUAWEI ALE-CL00 Build/HuaweiALE-CL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043024 Safari/537.36 MicroMessenger/6.5.4.1000 NetType/4G Language/zh_CN',
  'HTTP_ACCEPT' => '*/*',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch, br',
  'HTTP_REFERER' => 'http://wx.taitaiqi.cn/addon/LdhQguess/mobile/pay_pay/mpid/1.jsp',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4',
  'HTTP_HOST' => '/',
  'HTTP_CONNECTION' => 'keep-alive',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496302230.043031,
  'REQUEST_TIME' => 1496302230,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> <?php 
 //2017-06-01 15:45:55
//++++++++++++++++++++++++++++++++++++++++++++++
array (
  'USER' => 'www',
  'HOME' => '/home/www',
  'FCGI_ROLE' => 'RESPONDER',
  'SCRIPT_FILENAME' => '/www/wwwroot///index.php',
  'QUERY_STRING' => 's=/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'REQUEST_METHOD' => 'GET',
  'CONTENT_TYPE' => '',
  'CONTENT_LENGTH' => '',
  'SCRIPT_NAME' => '/index.php',
  'REQUEST_URI' => '/addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'DOCUMENT_URI' => '/index.php',
  'DOCUMENT_ROOT' => '/www/wwwroot//',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_SCHEME' => 'http',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_SOFTWARE' => 'nginx/1.12.0',
  'REMOTE_ADDR' => '101.226.66.174',
  'REMOTE_PORT' => '46179',
  'SERVER_ADDR' => '10.0.0.14',
  'SERVER_PORT' => '80',
  'SERVER_NAME' => 'www.qq.com',
  'REDIRECT_STATUS' => '200',
  'PATH_INFO' => 'addon/LdhQguess/mobile/getopenid/mpid/1/pid/10',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Mobile/14D27 MicroMessenger/6.5.5 NetType/WIFI Language/en',
  'HTTP_ACCEPT' => '*/*',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch, br',
  'HTTP_REFERER' => 'http://wx.taitaiqi.cn/addon/LdhQguess/mobile/index/mpid/1/pid/10',
  'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4',
  'HTTP_HOST' => '/',
  'HTTP_CONNECTION' => 'keep-alive',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1496303155.4290631,
  'REQUEST_TIME' => 1496303155,
)
//++++++++++++++++++++++++++++++++++++++++++++++
 
    ?> 